export const MOBILE_MONEY_CTE = `
MobileMoneyOperations AS (
  SELECT
    CAST(COALESCE(ca.COD_AGENCE, compte.COD_AGENCE, CASE WHEN o.NUM_TRANS LIKE 'A[0-9][0-9]%' THEN LEFT(o.NUM_TRANS, 3) END) AS varchar(20)) COLLATE DATABASE_DEFAULT AS agencyCode,
    CAST(COALESCE(NULLIF(o.KP_CAIS_AGENCE, ''), 'SANS-CAISSE') AS varchar(40)) COLLATE DATABASE_DEFAULT AS cashDeskKey,
    CAST(COALESCE(NULLIF(ca.COD_CAIS, ''), 'N/A') AS varchar(20)) COLLATE DATABASE_DEFAULT AS cashDeskCode,
    CAST(o.NUM_TRANS AS varchar(80)) COLLATE DATABASE_DEFAULT AS operationNumber,
    CAST(o.NUM_TRANS AS varchar(80)) COLLATE DATABASE_DEFAULT AS operationId,
    CAST(o.BORDEREAU AS varchar(80)) COLLATE DATABASE_DEFAULT AS receiptNumber,
    CAST(o.COD_TYP_OPERAT AS varchar(30)) COLLATE DATABASE_DEFAULT AS operationCode,
    CAST(CASE
      WHEN LTRIM(RTRIM(ISNULL(o.COD_TYP_OPERAT, ''))) = 'MOD1' THEN 'wallet-to-bank'
      WHEN LTRIM(RTRIM(ISNULL(o.COD_TYP_OPERAT, ''))) = 'MOR1' THEN 'bank-to-wallet'
    END AS varchar(30)) COLLATE DATABASE_DEFAULT AS mobileMoneyType,
    CAST(CASE
      WHEN LTRIM(RTRIM(ISNULL(o.COD_TYP_OPERAT, ''))) = 'MOD1' THEN N'Depot Wallet to Bank'
      WHEN LTRIM(RTRIM(ISNULL(o.COD_TYP_OPERAT, ''))) = 'MOR1' THEN N'Retrait Bank to Wallet'
    END AS nvarchar(120)) COLLATE DATABASE_DEFAULT AS mobileMoneyLabel,
    CAST(CASE
      WHEN LTRIM(RTRIM(ISNULL(o.COD_TYP_OPERAT, ''))) = 'MOD1' THEN 'IN'
      WHEN LTRIM(RTRIM(ISNULL(o.COD_TYP_OPERAT, ''))) = 'MOR1' THEN 'OUT'
    END AS varchar(3)) COLLATE DATABASE_DEFAULT AS direction,
    CAST(ISNULL(o.MONTANT, 0) AS money) AS amount,
    CAST(o.DATE_OPERATION AS datetime) AS operationDate,
    CAST(o.NUM_CPTE AS varchar(22)) COLLATE DATABASE_DEFAULT AS accountNumber,
    CAST(compte.INTITULE_CPTE AS nvarchar(220)) COLLATE DATABASE_DEFAULT AS accountLabel,
    CAST(compte.INTITULE_CPTE AS nvarchar(220)) COLLATE DATABASE_DEFAULT AS customerName,
    CAST(o.COD_UTIL AS varchar(50)) COLLATE DATABASE_DEFAULT AS userCode,
    CAST(o.DESCRIPTION AS nvarchar(320)) COLLATE DATABASE_DEFAULT AS description,
    CAST(o.NUM_CHEQUE AS varchar(80)) COLLATE DATABASE_DEFAULT AS chequeNumber,
    CAST(o.CODE_DEVISE AS varchar(10)) COLLATE DATABASE_DEFAULT AS currencyCode
  FROM dbo.OPERATION o WITH (NOLOCK)
  LEFT JOIN dbo.CAIS_AGENCE ca WITH (NOLOCK)
    ON ca.KP_CAIS_AGENCE = o.KP_CAIS_AGENCE
  LEFT JOIN dbo.COMPTES compte WITH (NOLOCK)
    ON compte.NUM_CPTE COLLATE DATABASE_DEFAULT = o.NUM_CPTE COLLATE DATABASE_DEFAULT
  WHERE o.DATE_OPERATION >= @AsOfDate
    AND o.DATE_OPERATION < DATEADD(DAY, 1, @AsOfDate)
    AND LTRIM(RTRIM(ISNULL(o.COD_TYP_OPERAT, ''))) IN ('MOD1', 'MOR1')
    AND (
      (LTRIM(RTRIM(ISNULL(o.COD_TYP_OPERAT, ''))) = 'MOD1' AND o.NUM_TRANS LIKE '%AOP%')
      OR (LTRIM(RTRIM(ISNULL(o.COD_TYP_OPERAT, ''))) = 'MOR1' AND o.NUM_TRANS LIKE '%AOC%')
    )
)`;
